name: Workflow success
description: Validate correct run of workflow
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Check all job status
      # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
      # see https://stackoverflow.com/a/67532120/4907315
      if: >-
        ${{

             contains(needs.*.result, 'failure')
          || contains(needs.*.result, 'cancelled')
          || contains(needs.*.result, 'skipped')
        }}
      run: exit 1
      shell: bash
