name: Auto-merge
description: Auto-merge PR's from dependabot
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Squash and Merge PR from dependabot
      uses: fastify/github-action-merge-dependabot@v3.11.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: squash
