name: Auto-merge
description: Auto-merge PR's from dependabot
inputs:
  github-token:
    description: "GitHub token for deployment"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Squash and Merge PR from dependabot
      uses: fastify/github-action-merge-dependabot@v3.11.0
      with:
        github-token: ${{ inputs.github-token }}
        merge-method: squash
