name: Install poetry
description: Install python, poetry and tox
inputs:
  python-version:
    description: "Python version to use"
    default: "3.11"
  poetry-version:
    description: "Poetry version to use"
    default: "1.8.3"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: ${{ inputs.poetry-version }}
    - name: Install tox
      shell: bash
      run: pip install tox
