name: End to end test python code
on:
  workflow_call:
    inputs:
      python-version:
        default: "3.11"
        type: string
      poetry-version:
        default: "1.8.3"
        type: string
    secrets:
      e2e_username:
        required: true
      e2e_password:
        required: true
jobs:
  e2e-test:
    name: End to End testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend-name:
          - Stubbed
          - QX emulator
    env:
      E2E_USERNAME: ${{ secrets.e2e_username }}
      E2E_PASSWORD: ${{ secrets.e2e_password }}
    steps:
      - uses: actions/checkout@v4
      - uses: QuTech-Delft/GitHub-Actions/poetry-setup@fix/QI2-1219/fix-failing-action-import
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
      - uses: actions/checkout@v4
      - name: Install packages
        run: poetry install
      - name: Run e2e test
        run: poetry run python tests/e2e_test.py "${{ matrix.backend-name }}"
