name: Auto-merge PR's from dependabot
on:
  workflow_call:
jobs:
  auto-merge-dependabot:
    name: Auto merge dependabot PR
    if: ${{ (github.event_name == 'pull_request') && (github.actor == 'dependabot[bot]') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Squash and Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.11.0
        with:
          github-token: ${{ secrets.github_token }}
          merge-method: squash
