name: Unit test python code
on:
  workflow_call:
    inputs:
      python-version:
        default: "3.11"
        type: string
      poetry-version:
        default: "1.8.3"
        type: string
jobs:
  unit-test:
    name: Unit testing
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.9
          - 3.10
          - 3.11
          - 3.12
        os-version:
          - ubuntu-latest
          - macos-13
          - macos-14
          - windows-latest
    runs-on: ${{ matrix.os-version }}
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - uses: actions/checkout@v4
      - uses: QuTech-Delft/GitHub-Actions/poetry-setup@fix/QI2-1219/fix-failing-action-import
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
      - uses: actions/checkout@v4
      - name: run tox test
        run: tox -e test
