name: Tests
on:
  workflow_call:
    inputs:
      python-version:
        default: "3.11"
        type: string
      poetry-version:
        default: "1.8.3"
        type: string
      e2e_path:
        type: string
        required: true
      idp_url:
        type: string
        default: "https://quantum-inspire-staging.eu.auth0.com"
      api_audience:
        type: string
        default: "compute-job-manager"
      default_host:
        type: string
        default: "https://staging.qi2.quantum-inspire.com"
    secrets:
      e2e_username:
        required: true
      e2e_password:
        required: true
      idp_client_id:
        required: true

jobs:
  lint:
    uses: qutech-delft/github-actions/.github/workflows/_tox-lint.yaml@master
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}
  unit-test:
    uses: qutech-delft/github-actions/.github/workflows/_tox-unit-test.yaml@master
    with:
      poetry-version: ${{ inputs.poetry-version }}
  e2e-test:
    uses: qutech-delft/github-actions/.github/workflows/_custom-e2e-test.yaml@master
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}
      e2e_path: ${{ inputs.e2e_path }}
      idp_url: ${{ inputs.idp_url }}
      api_audience: ${{ inputs.api_audience }}
      default_host: ${{ inputs.default_host }}
    secrets:
      e2e_username: ${{ secrets.e2e_username }}
      e2e_password: ${{ secrets.e2e_password }}
      idp_client_id: ${{ secrets.idp_client_id }}
  complete:
    uses: qutech-delft/github-actions/.github/workflows/_custom-validation.yaml@master
    needs: [lint, unit-test, e2e-test]
  auto-merge-dependabot:
    uses: qutech-delft/github-actions/.github/workflows/_dependabot-auto-merge.yaml@master
    needs: complete
